
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MY
 */
public class Doctors_Reg extends javax.swing.JFrame {

    /**
     * Creates new form Doctors_Re
     */
    public Doctors_Reg() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Dname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        spec = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        regno = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        suited = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(500, 250));
        setPreferredSize(new java.awt.Dimension(600, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setText("DOCTOR'S REGISTRATION");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(305, 16, 329, 45);

        jLabel2.setText("DOCTOR'S NAME:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(47, 77, 131, 39);
        getContentPane().add(Dname);
        Dname.setBounds(184, 83, 269, 26);

        jLabel3.setText("SPECIALITY:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(47, 128, 94, 20);

        spec.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cardiologist", "General physician", "Pediatrician" }));
        getContentPane().add(spec);
        spec.setBounds(147, 125, 246, 26);

        jLabel4.setText("DOC REG:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(47, 160, 152, 43);
        getContentPane().add(regno);
        regno.setBounds(205, 168, 197, 26);

        jButton1.setText("CREATE ACCOUNT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(148, 313, 171, 29);

        jLabel7.setText("LOCATION:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(47, 212, 86, 31);
        getContentPane().add(suited);
        suited.setBounds(148, 214, 122, 26);

        pack();
    }// </editor-fold>//GEN-END:initComponents
         String name="root";
         String speciality="root";
         String Regno="root";
         
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        GeneralP p=new GeneralP();
        p.setVisible(true);
        this.dispose();
        String querry = "insert into doctor (doctor's name, speciality,doctors reg,Location) values (?,?,?,?)";
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/datetests","root","");
        } catch (SQLException ex) {
             System.out.println("Error: " + ex.getMessage());
        }
        
        try {
            PreparedStatement pst = con.prepareStatement(querry);
            pst.setString(1,Dname.getText());
            pst.setString(2,spec.getItemAt(WIDTH));
            pst.setString(1,regno.getText());
            pst.setString(2,suited.getText());
            pst.executeUpdate();
            System.out.println("done");
            
        } catch (SQLException ex) {
            System.out.println("Error" + ex.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Doctors_Reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Doctors_Reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Doctors_Reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Doctors_Reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Doctors_Reg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Dname;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField regno;
    private javax.swing.JComboBox<String> spec;
    private javax.swing.JTextField suited;
    // End of variables declaration//GEN-END:variables

    private static class con {

        private static PreparedStatement prepareStatement(String querry) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        public con() {
        }
    }

    private static class Int {

        public Int() {
        }
    }
}
