
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MY
 */
public class Registration extends javax.swing.JFrame {

    /**
     * Creates new form Registration
     */
    public Registration() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        firstname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        secondname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        date = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        month = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        year = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        gender = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        jLabel12 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();

        jTextField3.setText("jTextField3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(500, 250));
        setPreferredSize(new java.awt.Dimension(950, 950));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("REGISTRATION");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(290, 10, 190, 50);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("FIRST NAME:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(55, 75, 168, 49);
        getContentPane().add(firstname);
        firstname.setBounds(229, 75, 210, 49);

        jLabel3.setText("LAST NAME:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(473, 75, 92, 49);
        getContentPane().add(secondname);
        secondname.setBounds(571, 75, 207, 49);

        jLabel4.setText("DATE OF BIRTH:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(44, 169, 123, 55);

        jLabel5.setText("DATE:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(182, 186, 83, 20);

        date.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateActionPerformed(evt);
            }
        });
        getContentPane().add(date);
        date.setBounds(271, 183, 49, 26);

        jLabel6.setText("MONTH:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(326, 186, 110, 20);

        month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "JANUARY", "FEBUARY", "MARCH", "APRIL", "MAY", "JUNE", "JULY", "AUGUST", "SEPTEMBER", "OCTOBER", "NOVEMBER", "DECEMBER" }));
        getContentPane().add(month);
        month.setBounds(442, 183, 117, 26);

        jLabel7.setText("YEAR:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(577, 186, 46, 20);

        year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017" }));
        getContentPane().add(year);
        year.setBounds(641, 183, 67, 26);

        jLabel8.setText("GENDER:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(55, 293, 121, 49);

        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Female", "Male" }));
        getContentPane().add(gender);
        gender.setBounds(182, 304, 81, 26);

        jLabel9.setText("USERNAME:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(55, 358, 88, 46);
        getContentPane().add(username);
        username.setBounds(149, 358, 320, 46);

        jLabel10.setText("EMAIL ADDRESS:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(74, 448, 127, 45);
        getContentPane().add(email);
        email.setBounds(207, 445, 481, 51);

        jLabel11.setText("CREATE PASSWORD:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(55, 541, 268, 61);
        getContentPane().add(password);
        password.setBounds(330, 560, 287, 30);

        jLabel12.setText("CONFIRM PASSWORD:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(55, 639, 280, 50);
        getContentPane().add(jPasswordField2);
        jPasswordField2.setBounds(330, 650, 275, 30);
        jPasswordField2.getAccessibleContext().setAccessibleParent(password);

        jButton1.setText("SIGN UP");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(278, 787, 95, 29);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateActionPerformed

    }//GEN-LAST:event_dateActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  Login l=new Login();
  l.setVisible(true);
  this.dispose();
         //String querry = "insert into patient (column1, column2,column3,column4,column5,column6,column7) values (?,?,?,?,?,?,?)";
       /* try {
            
           Connection con = DriverManager.getConnection("jdbc:mysql://localhost/rapido","root","");
            System.out.println("connected!");
            
           String insert="INSERT INTO 'rapido','patient'('firstname','lastname','dob','gender','emailaddress','username','password')VALUES ('"+firstname+"','"+secondname+"','"+date+"','"+gender+"','"+email+"')";
            
        } catch (java.sql.SQLException ex) {
             System.out.println("Error: " + ex.getMessage());
        }
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:http://localhost/rapido","root","");
            System.out.println("connected!");
        try {
           String insert="INSERT INTO 'rapido','patient'('firstname','lastname','dob','gender','emailaddress','username','password')VALUES ('"+firstname+"','"+secondname+"','"+date+"','"+gender+"','"+email+"')";
            PreparedStatement pst = con.prepareStatement(insert);
            pst.setString(1,firstname.getText());
            pst.setString(2,secondname.getText());
            pst.setString(3,date.getSelectedItem().toString());
            pst.setString(3,month.getSelectedItem().toString());
            pst.setString(3,year.getSelectedItem().toString());
            pst.setString(4,gender.getSelectedItem().toString());
            pst.setString(5,email.getText());
            pst.executeUpdate();
            System.out.println("done");
                        
        } catch (java.sql.SQLException ex) {
            System.out.println("Error" + ex.getMessage());
        }*/
  Connection con = null;
  String querry = "INSERT INTO 'rapido','patient'('firstname','lastname','dob','gender','emailaddress','username','password')VALUES ('"+firstname+"','"+secondname+"','"+date+"','"+gender+"','"+email+"')";
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/datetests","root","");
        } catch (SQLException ex) {
             System.out.println("Error: " + ex.getMessage());
        }
        
        try {
            PreparedStatement pst = con.prepareStatement(querry);
            pst.setString(1,firstname.getText());
            pst.setString(2,secondname.getText());
            pst.setString(3,date.getSelectedItem().toString());
            pst.setString(3,month.getSelectedItem().toString());
            pst.setString(3,year.getSelectedItem().toString());
            pst.setString(4,gender.getSelectedItem().toString());
            pst.setString(5,email.getText());
            pst.executeUpdate();
            System.out.println("done");
            
        } catch (SQLException ex) {
            System.out.println("Error" + ex.getMessage());
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

  // jdbc:derby://localhost:1527/RapidoDB [AsyaLoise on APP//
     
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration().setVisible(true);
            }
            //Connection con=DriverManager.getconnection("jdbc:derby://localhost:1527/RapidoDB","AsyaLoise","");
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> date;
    private javax.swing.JTextField email;
    private javax.swing.JTextField firstname;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JComboBox<String> month;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField secondname;
    private javax.swing.JTextField username;
    private javax.swing.JComboBox<String> year;
    // End of variables declaration//GEN-END:variables
}
